site_name: Shiyd's blog
site_url: 
site_author: Shiyd
site_description: >-
  Shiyd's blog

# Repository
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 Shiyd

# Configuration
theme:
  name: material
  custom_dir: theme
  favicon: assets/favicon.ico


  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en

  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

    # insiders only
    # - content.code.annotate
    # - content.tabs.link
    # - navigation.indexes
    # - navigation.tabs.sticky
    # - navigation.tracking

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/git-alt
  logo: 
    assets/break.png

# Plugins
plugins:
  - search:
      lang: ja
  - git-revision-date-localized
  - minify:
      minify_html: true

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

extra_javascript:
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js

# Extensions
markdown_extensions:
  - admonition:
  - abbr:
  - attr_list:
  - def_list:
  - footnotes:
  - md_in_html:
  - meta:
  - markdown.extensions.smarty:
      smart_quotes: false
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
  - pymdownx.betterem:
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      extend_pygments_lang:
      - name: php-inline
        lang: php
        options:
          startinline: true
      - name: pycon3
        lang: pycon
        options:
          python3: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      normalize_issue_symbols: true
  - pymdownx.mark:
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tilde:
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.progressbar:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path:
      auto_append:
      check_paths: true
  - pymdownx.saneheaders:

docs_dir: docs

# Page tree
nav:
  - Home: 
    - Getting Started: index.md
  - Weekly Report:
    - Aug:
      - Survey of GNN in CO: weekly-report/aug/Survey_GNN_CO.md
    - Sept: 
      - InfGCN: weekly-report/sept/InfGCN.md
      - DISCO: weekly-report/sept/DISCO.md
      - DeepIS: weekly-report/sept/DeepIS.md
      - DIEM: weekly-report/sept/DIEM.md
    - Oct: 
      - SampleG: weekly-report/oct/SampleG.md
      - MCIM: weekly-report/oct/MCIM.md
      - DQN4Signed: weekly-report/oct/DQN4Signed.md
      - RW Sample: weekly-report/oct/RW_Sample.md
    - Nov:
      - GLIE: weekly-report/nov/GLIE.md
      - DRL4IM: weekly-report/nov/DRL4IM.md
      - NoveltyDecay: weekly-report/nov/NoveltyDecay.md
      - TimeDiscounted: weekly-report/nov/TimeDiscounted.md
    - Dec:
      - N-Family: weekly-report/dec/N-Family.md
  - Note:
    - PaperList:
      - LatestIMPaper: note/paperlist/Latest_IM_Papers.md
  - Subject:
    - IMwithRL:
      - S2V-DQN: subject/IMwithDRL/S2V-DQN.md
      - GCOMB: subject/IMwithDRL/GCOMB.md
      - DISCO: subject/IMwithDRL/DISCO.md
      - Topic-Aware: subject/IMwithDRL/DIEM.md
      - Contingency: subject/IMwithDRL/Contingency.md
      - GRIM: subject/IMwithDRL/GRIM.md
